export const songList = [
  {
    artist: "thiaguinho",
    songs: [
      "pela-vida-inteira",
      "pe-na-areia",
      "pot",
      "caraca-muleke!",
      "preciso-desabafar",
      "como-nunca-amei-ninguem",
      "em-busca-da-minha-sorte",
      "minha-razao-de-viver",
      "a-fila-anda",
      "ousadia-e-alegria",
    ],
  },
  {
    artist: "revelacao",
    songs: [
      "coracao-radiante",
      "deixa-acontecer",
      "ta-escrito",
      "grades-do-coracao",
      "deixa-acontecer",
    ],
  },
  {
    artist: "raca-negra",
    songs: [
      "cheia-de-manias",
      "cigana",
      "tao-seu",
      "cigana",
      "cheia-de-manias",
    ],
  },
  {
    artist: "exaltasamba",
    songs: [
      "ta-vendo-aquela-lua",
      "me-apaixonei-pela-pessoa-errada",
      "fugidinha",
      "telegrama",
      "louca-paixao",
      "calma-amor",
      "teu-segredo",
      "nem-pensar",
      "me-apaixonei-pela-pessoa-errada",
      "gamei",
      "desliga-e-vem",
      "louca-paixao",
      "e-voce",
      "oposto-do-meu-ser",
      "quero-sentir-de-novo",
      "me-apaixonei-pela-pessoa-errada",
    ],
  },
  {
    artist: "grupo-fundo-de-quintal",
    songs: [
      "o-show-tem-que-continuar",
      "conselho",
      "nao-tem-menos-semelhante",
      "nao-tem-menos-semelhante",
      "prazer-da-serrinha",
      "te-gosto",
      "a-batucada-dos-nossos-tantas",
    ],
  },
  {
    artist: "pixote",
    songs: [
      "inseguranca",
      "mande-um-sinal",
      "coisas-do-amor-fa-de-carteirinha",
      "pot",
      "inseguranca",
      "o-amor-nao-tem-culpa",
      "nuance",
      "inseguranca",
      "nem-de-graca",
    ],
  },
  {
    artist: "so-pra-contrariar",
    songs: [
      "que-se-chama-amor",
      "essa-tal-liberdade",
      "mineirinho",
      "depois-do-prazer",
      "essa-tal-liberdade",
      "depois-do-prazer",
      "nosso-sonho-nao-e-ilusao",
      "que-se-chama-amor",
    ],
  },
  {
    artist: "molejo",
    songs: [
      "cilada",
      "danca-da-vassoura",
      "familia",
      "paparico",
      "brincadeira-de-crianca",
      "cilada",
    ],
  },
  {
    artist: "jorge-aragao",
    songs: [
      "eu-e-voce-sempre",
      "identidade",
      "topo-das-licoes",
      "eu-e-voce-sempre",
      "eu-e-voce-sempre",
      "partido-alto",
      "identidade",
      "ja-e",
      "do-fundo-do-nosso-quintal",
    ],
  },
  {
    artist: "art-popular",
    songs: [
      "temporal",
      "pimpolho",
      "sem-abuso",
      "primeiro-beijo",
      "agamamou",
      "eternamente-feliz",
      "utopia",
      "valeu-demais",
      "percepcao",
      "oa-oa-cancao-do-amor",
      "o-canto-da-razao",
    ],
  },
  {
    artist: "turma-do-pagode",
    songs: [
      "camisa-10",
      "desliga-e-vem",
      "a-gente-ja-nao-rola",
      "fato-consumado",
      "bebe-e-vem-me-procurar",
      "sua-mae-vai-me-amar",
      "aonde-quer-chegar",
    ],
  },
  { artist: "vava-e-marcio", songs: ["morango-do-nordeste"] },
  {
    artist: "sorriso-maroto",
    songs: [
      "assim-voce-mata-o-papai",
      "tenho-medo",
      "a-primeira-namorada",
      "dependente",
      "futuro-prometido",
      "fica-combinado-assim",
      "coracao-deserto",
      "ainda-gosto-de-voce",
      "pra-mim-nao-e",
      "assim-voce-mata-o-papai",
    ],
  },
  {
    artist: "katinguele",
    songs: [
      "inarai",
      "recado-a-minha-amada",
      "no-compasso-do-criador",
      "engracadinha",
      "no-compasso-do-criador",
      "pot",
      "mundo-dos-sonhos",
    ],
  },
  {
    artist: "zeca-pagodinho",
    songs: [
      "deixa-a-vida-me-levar",
      "vai-vadiar",
      "ogum",
      "deixa-a-vida-me-levar",
      "deixa-a-vida-me-levar",
      "faixa-amarela",
      "coracao-em-desalinho",
      "verdade",
      "vacilao",
    ],
  },
  { artist: "akatu", songs: ["ta-escrito"] },
  {
    artist: "salgadinho",
    songs: [
      "compasso-do-amor",
      "me-leva-junto-com-voce",
      "ainda-resta-uma-bagagem",
    ],
  },
  {
    artist: "alexandre-pires",
    songs: ["domingo", "eu-e-ela", "marrom-bombom", "domingo"],
  },
  {
    artist: "soweto",
    songs: [
      "farol-das-estrelas",
      "mundo-de-oz",
      "farol-das-estrelas",
      "estrela-da-paz",
      "dere",
      "buzios-e-taro",
      "angela",
      "maca-do-amor",
    ],
  },
  {
    artist: "alcione",
    songs: [
      "estranha-loucura",
      "nao-deixe-o-samba-morrer",
      "meu-ebano",
      "figa-de-guine",
      "sufoco",
      "gostoso-veneno",
    ],
  },
  {
    artist: "grupo-raca",
    songs: [
      "eu-e-ela",
      "seja-mais-voce",
      "mulher-de-amigo-meu",
      "seja-mais-voce",
      "dona-da-minha-sina",
    ],
  },
  {
    artist: "pericles",
    songs: [
      "insensato-destino",
      "supera",
      "diz-pra-mim",
      "oa-oa-cancao-de-amor",
      "lembranca",
      "supera",
      "graveto",
      "pupila",
    ],
  },
  { artist: "belo", songs: ["dere"] },
  { artist: "karametade", songs: ["morango-do-nordeste", "decisao"] },
  {
    artist: "arlindo-cruz",
    songs: [
      "o-show-tem-que-continuar",
      "meu-lugar",
      "meu-nome-e-favela",
      "chegamos-ao-fim",
      "o-que-e-o-amor",
    ],
  },
  { artist: "os-morenos", songs: ["marrom-bombom", "marrom-bombom"] },
  {
    artist: "os-travessos",
    songs: [
      "maravilha-te-amar",
      "to-te-filmando-sorria",
      "sonhos-e-planos-sou-eu",
      "quando-a-gente-ama",
      "maravilha-te-amar",
      "um-dia-pra-nos-dois",
    ],
  },
  {
    artist: "dilsinho",
    songs: [
      "refem",
      "pessimo-negocio",
      "sogra",
      "pouco-a-poucofeat.-sorriso-maroto",
    ],
  },
  { artist: "grupo-100%", songs: ["hoje-vou-pagodear:-bate-tan-tan"] },
  { artist: "wagninho", songs: ["gente-da-gente-30-e-poucos-anos"] },
  { artist: "waguinho", songs: ["mina-de-fe"] },
  { artist: "jeito-moleque", songs: ["pela-vida-inteira"] },
  {
    artist: "negritude-junior",
    songs: ["beijo-geladinho", "conto-de-fadas", "timidez", "sabor-morango"],
  },
  { artist: "bokaloka", songs: ["duas-paixoes"] },
  {
    artist: "pique-novo",
    songs: [
      "pra-te-conquistar",
      "mel-na-boca",
      "eu-tenho-muito-mais",
      "porradao",
    ],
  },
  { artist: "swing-e-simpatia", songs: ["encaixe-perfeito"] },
  {
    artist: "grupo-malicia",
    songs: [
      "primeiro-beijo",
      "primeiro-beijo",
      "sentinela",
      "nada-vai-nos-separar",
    ],
  },
  {
    artist: "grupo-sensacao",
    songs: [
      "coral-de-anjos",
      "velho-amor",
      "demoro",
      "preciso-desse-mel",
      "coral-de-anjos",
      "sabor-do-teu-beijo",
    ],
  },
  { artist: "chrigor", songs: ["meu-jeito-de-amar"] },
  {
    artist: "bala-bombom-e-chocolate",
    songs: ["fissuras-de-um-casal", "fissuras-de-um-casal"],
  },
  { artist: "kiloucura", songs: ["meu-casamento", "conversa-fiada"] },
  { artist: "milthinho", songs: ["2022"] },
  { artist: "ludmilla", songs: ["maliciosa", "maldivas"] },
  { artist: "samba-de-dom", songs: ["problema-emocional"] },
  { artist: "intimistas", songs: ["deixa-alagar"] },
  { artist: "vitinho", songs: ["sem-perceber", "cansei"] },
  { artist: "ta-na-mente", songs: ["dorme-com-deus"] },
  { artist: "marvvila", songs: ["cancao-da-despedida"] },
  { artist: "billy-sp", songs: ["domino", "timidez"] },
  { artist: "gamadinho", songs: ["por-favor", "morando-em-seu-olhar"] },
  { artist: "caju-pra-baixo", songs: ["trajetoria"] },
  { artist: "victor-alves", songs: ["envolvidao"] },
  { artist: "mc-marks", songs: ["da-trabalho"] },
  { artist: "mc-ryan-sp", songs: ["set-nino-abravanel"] },
  { artist: "grupo-bom-astral", songs: ["anjo-meu"] },
  { artist: "di-proposito", songs: ["ponto-fraco", "manda-audio"] },
  {
    artist: "grupo-clareou",
    songs: ["dona-dos-meus-sonhos", "nada-pra-fazer"],
  },
  { artist: "tiee", songs: ["pago-pra-ver", "o-som-do-tambor"] },
  { artist: "samba-da-ladeira", songs: ["beijando"] },
  { artist: "rodriguinho", songs: ["to-com-saudade"] },
  { artist: "grupo-benzadeus", songs: ["tuntuntun", "tuntuntun"] },
  {
    artist: "mumuzinho",
    songs: ["trajetoria", "porradao", "tomara", "eu-mereco-ser-feliz"],
  },
  { artist: "vitor-souza", songs: ["oya"] },
  { artist: "grupo-fala-comigo", songs: ["lugarzinho", "problema-emocional"] },
  { artist: "fm-o-dia", songs: ["e-agora"] },
  { artist: "suel", songs: ["me-redimir"] },
  { artist: "marquinhos-sensacao", songs: ["pra-gente-se-encontrar-de-novo"] },
  { artist: "vinny-santa-fe", songs: ["castelo-de-um-quarto-so"] },
  { artist: "robinho", songs: ["fala"] },
  { artist: "rdn", songs: ["meu-casamento"] },
  {
    artist: "so-preto-sem-preconceito",
    songs: ["coisa-mais-linda", "e-tanta"],
  },
  { artist: "adryana-e-a-rapaziada", songs: ["fim-de-noite"] },
  { artist: "grupo-refla", songs: ["alimenta-meu-sonho", "caminhos"] },
  { artist: "juventude-s", songs: ["historia-de-amor"] },
  {
    artist: "leci-brandao",
    songs: ["so-quero-te-namorar", "agenda", "deixa-pra-la", "ze-do-caroco"],
  },
  {
    artist: "sem-compromisso",
    songs: ["mariana-parte-minha", "nascente", "felicidade-perdida"],
  },
  { artist: "eliana-de-lima", songs: ["desejo-de-amar"] },
  { artist: "ronaldo-e-os-barcellos", songs: ["feliz-aniversario"] },
  { artist: "reinaldo", songs: ["retrato-cantado-de-um-amor"] },
  { artist: "grupo-katinguele", songs: ["cilada-c-1995", "apelo-de-quem-ama"] },
  { artist: "muleke-travesso", songs: ["voce-em-mim"] },
  { artist: "dhema", songs: ["sonho-nao-pode-acabar"] },
  { artist: "biro-do-cavaco", songs: ["jessica"] },
  { artist: "toke-divinal", songs: ["pequena-princesa"] },
  { artist: "cor-da-pele", songs: ["eu-te-amo", "desengano"] },
  {
    artist: "da-melhor-qualidade",
    songs: ["universo-de-prazer", "universo-de-prazer"],
  },
  { artist: "um-toque-a-mais", songs: ["vida-bandida"] },
  { artist: "grupo-ed", songs: ["video-clip"] },
  { artist: "douglas-sampa", songs: ["flagrante"] },
  {
    artist: "grupo-menos-e-mais",
    songs: ["pot", "adorei", "pot", "quando-voce-me-beija"],
  },
  {
    artist: "atitude-67",
    songs: ["cerveja-de-garrafa-fumaca-que-eu-faco", "saideira"],
  },
  {
    artist: "os-baroes-da-pisadinha",
    songs: ["recairei", "ta-rocheda", "amor-da-despedida"],
  },
  {
    artist: "henrique-e-juliano",
    songs: ["arranhao", "ficamento", "gaiola", "de-garrafa-a-pior"],
  },
  {
    artist: "israel-e-rodolffo",
    songs: ["batom-de-cereja", "so-de-sacanagem"],
  },
  { artist: "matheus-fernandes", songs: ["baby-me-atende"] },
  {
    artist: "rai-saia-rodada",
    songs: ["tapao-na-raba", "bebe-e-vem-me-procurar"],
  },
  { artist: "joao-gomes", songs: ["meu-pedaco-de-pecado"] },
  { artist: "felipe-araujo", songs: ["atrasadinha"] },
  {
    artist: "tarcisio-do-acordeon",
    songs: ["meia-noite-voce-tem-meu-whatsapp", "nega"],
  },
  {
    artist: "marilia-mendonca",
    songs: [
      "supera",
      "troca-de-calcada",
      "bebi-liguei",
      "todo-mundo-vai-sofrer",
      "presepada",
    ],
  },
  {
    artist: "ze-neto-e-cristiano",
    songs: [
      "alo-ambev-segue-sua-vida",
      "ferida-curada",
      "largado-as-tracas",
      "vamo-tomar-uma",
      "bebi-minha-bicicleta-coracao-falido",
    ],
  },
  { artist: "joao-gustavo-e-murilo", songs: ["lencol-dobrado"] },
  {
    artist: "matheus-e-kauan",
    songs: ["quarta-cadeira", "litrao", "e-problema", "vagabundo"],
  },
  { artist: "mc-jacaré", songs: ["vento-forte"] },
  {
    artist: "wesley-safadao",
    songs: ["ele-e-ele-eu-sou-eu", "aquele-1%", "eu-ja-tava-bem", "passatempo"],
  },
  { artist: "mari-fernandez", songs: ["nao-nao-vou", "parada-louca"] },
  { artist: "jorge-e-mateus", songs: ["cheirosa", "tijolao"] },
  { artist: "vitor-fernandes", songs: ["acaso"] },
  { artist: "simone-e-simaria", songs: ["foi-pa-pum"] },
  { artist: "marcia-fellipe", songs: ["quem-me-dera"] },
  { artist: "guilherme-e-benuto", songs: ["sigilo"] },
  { artist: "mc-kevin-o-chris", songs: ["evoluiu"] },
  { artist: "lauana-prado", songs: ["cobaia"] },
  { artist: "felipe-original", songs: ["hit-contagiante"] },
  { artist: "leo-santana", songs: ["contatinho"] },
  { artist: "paulo-e-nathan", songs: ["acabei-de-terminar"] },
  { artist: "gustavo-mioto", songs: ["solteiro-nao-trai"] },
  { artist: "avine-vinny", songs: ["coracao-cachorro"] },
  { artist: "anitta", songs: ["some-que-ele-vem-atras"] },
  {
    artist: "diego-e-victor-hugo",
    songs: ["a-culpa-e-do-meu-grau-feat.-ze-neto-e-cristiano", "pisadinha"],
  },
  { artist: "joao-bosco-e-gabriel", songs: ["alo-ex"] },
  { artist: "alok", songs: ["liberdade-quando-o-grave-bate-forte"] },
  { artist: "mc-rogerinho", songs: ["so-voce"] },
  { artist: "bruno-e-marrone", songs: ["ultimo-beijo"] },
  { artist: "luan-santana", songs: ["sorria", "seu-doutor"] },
  { artist: "petter-ferraz", songs: ["amor-ou-o-litrao"] },
  {
    artist: "lucas-lucco",
    songs: ["amava-nada", "posto-24h-feat.-wesley-safadao"],
  },
  { artist: "gusttavo-lima", songs: ["carreira-solo", "quebrando-protocolo"] },
  { artist: "ze-felipe", songs: ["so-tem-eu"] },
  { artist: "murilo-huff", songs: ["esse-barulho"] },
  { artist: "dennis", songs: ["agora-e-tudo-meu"] },
  { artist: "douglas-e-vinicius", songs: ["figurinha"] },
  { artist: "sambabook", songs: ["sonho-meu"] },
  { artist: "diogo-nogueira", songs: ["poder-da-criacao"] },
  {
    artist: "dona-ivone-lara",
    songs: [
      "acreditar",
      "alguem-me-avisou",
      "alguem-me-avisou",
      "tendencia",
      "mas-quem-disse-que-eu-te-esqueco",
      "prea-comeu",
      "sorriso-negro-feat.-jorge-ben-jor",
      "cantei-so-pra-distrair",
      "se-o-caminho-é-meu",
      "enredo-do-meu-samba",
      "axe-de-ianga-pai-maior",
      "muro-das-lamentacoes",
      "lamento-negro",
      "na-propria-palma",
      "samba-de-roda-pra-salvadaor-nao-chora-meu-bem-feat.-gilberto-gil",
      "o-samba-nao-pode-parar",
      "canto-do-meu-viver",
      "forca-da-imaginacao-feat.-beth-carvalho",
      "sorriso-de-crianca",
      "adeus-de-um-poeta",
      "um-grande-sonho",
      "o-meu-amor-tem-preco",
      "coracao-por-que-choras?",
      "bodas-de-ouro",
      "os-cinco-bailes-da-historia-do-rio",
      "pra-você-voltar",
      "adeus-a-solidao",
      "minha-verdade",
      "alvorecer-feat.-netinho-de-paula",
      "resignação",
      "meu-fim-de-carnaval-nao-foi-ruim",
      "samba-de-rosa-pra-salvador",
      "nao-chora-nenem-feat.-martinho-da-vila",
      "rainha-quelê",
      "me-deixa-ficar",
      "nasci-pra-sonhar-e-cantar",
      "a-cigana",
      "candeeiro-da-vovo",
      "serra-dos-meus-sonhos-dourados",
      "o-imperio-tocou-reunir",
      "por-querer-liberdade",
      "doces-recordações",
      "a-forca-do-criador",
      "sorriso-negro-feat.-jorge-ben-jor",
    ],
  },
  {
    artist: "beth-carvalho",
    songs: [
      "patrao-prenda-seu-gado",
      "vou-festejar",
      "andanca",
      "coisinha-do-pai",
    ],
  },
  { artist: "danilo-caymmi", songs: ["candeeiro-da-vovo"] },
  { artist: "nei-lopes", songs: ["senhora-da-cancao"] },
  { artist: "ze-renato", songs: ["candeeiro-da-vovo"] },
  {
    artist: "cartola",
    songs: [
      "preciso-me-encontrar",
      "o-mundo-e-um-moinho",
      "alvorada",
      "disfarca-e-chora",
      "as-rosas-nao-falam",
    ],
  },
  {
    artist: "chico-buarque",
    songs: [
      "cotidiano",
      "apesar-de-voce",
      "essa-moca-ta-diferente",
      "samba-e-amor",
      "samba-de-orly",
    ],
  },
  {
    artist: "os-originais-do-samba",
    songs: [
      "tenha-fe-pois-amanha-um-lindo-dia-vai-nascer",
      "falador-passa-mal",
      "enlouqueci",
      "esperancas-perdidas",
      "a-subida-do-morro",
    ],
  },
  { artist: "elis-regina", songs: ["tiro-ao-alvaro"] },
  {
    artist: "adoniran-barbosa",
    songs: [
      "trem-das-onze",
      "saudosa-maloca",
      "prova-de-carinho",
      "iracema",
      "samba-do-arnesto",
    ],
  },
  {
    artist: "nelson-cavaquinho",
    songs: [
      "juizo-final",
      "quando-eu-me-chamar-saudade",
      "a-flor-e-o-espinho",
      "tatuagem",
    ],
  },
  {
    artist: "martinho-da-vila",
    songs: [
      "disritmia",
      "mulheres",
      "canta-canta-minha-gente",
      "ex",
      "casa-de-bamba",
    ],
  },
  {
    artist: "clara-nunes",
    songs: [
      "tristeza-pe-no-chao",
      "canto-das-tres-racas",
      "o-mar-serenou",
      "conto-de-areia",
      "e-baiana",
    ],
  },
  { artist: "gonzaguinha", songs: ["o-que-e-o-que-e?", "e-vamos-a-luta"] },
  {
    artist: "paulinho-da-viola",
    songs: [
      "timoneiro",
      "duas-horas-da-manha",
      "danca-da-solidao",
      "roendo-as-unhas",
      "meu-mundo-e-hoje-eu-sou-assim",
    ],
  },
  {
    artist: "bezerra-da-silva",
    songs: [
      "malandragem-da-um-tempo",
      "a-semente",
      "a-fumaca-ja-subiu-pra-cuca",
      "sequestraram-minha-sogra",
      "bicho-feroz",
    ],
  },
  {
    artist: "joao-nogueira",
    songs: [
      "espelho",
      "um-gago-apaixonado",
      "poder-da-criacao",
      "as-forcas-da-natureza",
    ],
  },
  {
    artist: "benito-di-paula",
    songs: ["do-jeito-que-a-vida-quer", "retalhos-de-cetim"],
  },
  { artist: "almir-guineto", songs: ["conselho", "insensato-destino"] },
  {
    artist: "ze-keti",
    songs: [
      "a-voz-do-morro",
      "acender-as-velas",
      "diz-que-fui-por-ai",
      "opiniao",
    ],
  },
  {
    artist: "os-tincoas",
    songs: ["deixa-a-baiana-sambar", "arrasta-a-cadeira"],
  },
  {
    artist: "agepe",
    songs: [
      "deixa-eu-te-amar",
      "devagar-tambem-e-pressa",
      "na-onda-do-jornal",
      "me-leva",
    ],
  },
  {
    artist: "clementina-de-jesus",
    songs: ["marinheiro-so", "na-linha-do-mar"],
  },
  { artist: "neguinho-da-beija-flor", songs: ["gamacao-danada"] },
  { artist: "elton-medeiros", songs: ["pressentimento", "chove-e-nao-molha"] },
  { artist: "ruy-maurity", songs: ["nem-ouro-nem-prata"] },
  { artist: "jovelina-perola-negra", songs: ["sorriso-aberto"] },
  { artist: "elza-soares", songs: ["poe-pimenta"] },
];
