export const songList = [
  {
    artist: "exaltasamba-musicas",
    songs: [
      "e-no-pagode",
      "livre-pra-voar-quando-a-gente-se-encontrar",
      "ta-vendo-aquela-lua",
      "me-apaixonei-pela-pessoa-errada",
      "gamei",
      "telegrama",
      "jogo-de-seducao",
      "calma-amor",
      "valeu",
      "tchau-e-benca",
      "abandonado",
      "louca-paixao",
      "me-apaixonei-pela-pessoa-errada",
      "gamei",
      "telegrama",
      "cartao-postal",
    ],
  },
  {
    artist: "revelacao",
    songs: [
      "coracao-radiante",
      "deixa-acontecer",
      "ta-escrito",
      "fala-baixinho-shiii",
      "aventureiro",
      "deixa-acontecer",
      "compasso-do-amor",
      "so-vai-de-camarote",
      "grades-do-coracao",
    ],
  },
  { artist: "thiaguinho", songs: ["poderosa", "ponto-fraco"] },
  { artist: "reinaldo", songs: ["problema-emocional"] },
  {
    artist: "vitor-limma",
    songs: [
      "amor-de-fim-de-noite",
      "sou-o-cara-pra-voce",
      "amor-de-fim-de-noite",
    ],
  },
  {
    artist: "molejo",
    songs: [
      "voltei-feat-mumuzinho",
      "cilada-feat-nosso-sentimento",
      "cilada",
      "cacamba",
      "paparico",
      "brincadeira-de-crianca",
    ],
  },
  {
    artist: "zeca-pagodinho",
    songs: [
      "camarao-que-dorme-a-onda-leva",
      "toda-a-hora",
      "nao-sou-mais-disso",
      "maneiras",
      "ratatuia",
    ],
  },
  {
    artist: "ferrugem",
    songs: [
      "apaguei-pra-todos",
      "me-bloqueia",
      "apaguei-pra-todos",
      "interessante",
      "todo-amor-do-mundo",
    ],
  },
  { artist: "swing-e-simpatia", songs: ["toda-noite"] },
  { artist: "sorriso-maroto", songs: ["boa-noite", "sinais", "boa-noite"] },
  { artist: "tiee", songs: ["insensato-destino", "moca"] },
  { artist: "ludmilla", songs: ["falta-de-mim", "amor-dificil"] },
  {
    artist: "turma-do-pagode",
    songs: [
      "pente-e-rala",
      "lancinho",
      "camisa-10",
      "deixa-em-off",
      "a-gente-tem-tudo-a-ver",
    ],
  },
  {
    artist: "atitude-67",
    songs: [
      "que-beleza",
      "cerveja-de-garrafa-fumaca-que-eu-faco",
      "que-beleza",
      "saideira",
    ],
  },
  { artist: "dilsinho", songs: ["diferentao"] },
  { artist: "mari-fernandez", songs: ["cafe-na-cama"] },
  {
    artist: "pixote",
    songs: [
      "brilho-de-cristal",
      "mande-um-sinal",
      "ja-e-madrugada",
      "inseguranca",
      "brilho-de-cristal",
    ],
  },
  {
    artist: "jeito-moleque",
    songs: ["so-pro-meu-prazer", "eu-nunca-amei-assim"],
  },
  { artist: "kamisa-10", songs: ["nao-e-exagero"] },
  { artist: "lucas-morato", songs: ["de-guarda-baixa"] },
  {
    artist: "raca-negra",
    songs: ["cigana", "e-tarde-demais", "cheia-de-manias", "cigana"],
  },
  { artist: "belo", songs: ["desafio", "momentos", "farol-das-estrelas"] },
  { artist: "akatu", songs: ["cha-de-cama"] },
  {
    artist: "bokaloka",
    songs: ["que-situacao", "nao-pedi-pra-me-apaixonar", "shortinho-saint"],
  },
  {
    artist: "xande-de-pilares",
    songs: [
      "baixa-essa-guarda",
      "do-jeito-que-a-vida-quer",
      "so-depois",
      "clareou",
    ],
  },
  {
    artist: "jorge-aragao",
    songs: ["do-fundo-do-nosso-quintal", "eu-e-voce-sempre", "identidade"],
  },
  { artist: "doce-encontro", songs: ["alucinado"] },
  { artist: "pericles", songs: ["supera", "ate-que-durou", "beijo-doce"] },
  {
    artist: "art-popular",
    songs: [
      "megastar",
      "sem-abuso",
      "pimpolho",
      "temporal",
      "fricote",
      "amarelinha",
      "pimpolho",
      "sai-da-frente",
      "bombocado",
      "temporal",
    ],
  },
  { artist: "bom-gosto", songs: ["agora-perdeu"] },
  { artist: "fundo-de-quintal", songs: ["o-show-tem-que-continuar"] },
  { artist: "pyracao", songs: ["tudo-tem-saida"] },
  {
    artist: "so-pra-contrariar",
    songs: [
      "domingo",
      "out-door",
      "mineirinho",
      "domingo",
      "sai-da-minha-aba-bicao",
      "essa-tal-liberdade",
      "que-se-chama-amor",
      "depois-do-prazer",
    ],
  },
  { artist: "diogo-nogueira", songs: ["to-fazendo-a-minha-parte"] },
  { artist: "o-bem", songs: ["todo-amor-do-mundo"] },
  { artist: "katinguele", songs: ["inarai", "inarai", "recado-a-minha-amada"] },
  { artist: "toninho-geraes", songs: ["se-a-fila-andar"] },
  { artist: "mumuzinho", songs: ["fulminante"] },
  { artist: "inimigos-da-hp", songs: ["caca-e-cacador"] },
  { artist: "menos-e-mais", songs: ["vai-me-dando-corda"] },
  { artist: "gigantes-do-samba", songs: ["cigana"] },
  { artist: "os-morenos", songs: ["marrom-bombom"] },
  {
    artist: "raca",
    songs: ["o-teu-chamego", "eu-e-ela", "mulher-de-amigo-meu", "to-legal"],
  },
  { artist: "razao-brasileira", songs: ["vergonha-na-cara"] },
  {
    artist: "negritude-junior",
    songs: ["tanajura", "cohab-city", "beijo-geladinho"],
  },
  {
    artist: "os-travessos",
    songs: ["maravilha-te-amar", "to-te-filmando-sorria"],
  },
  { artist: "soweto", songs: ["maca-do-amor", "dere", "refem-do-coracao"] },
  { artist: "da-melhor-qualidade", songs: ["universo-de-prazer"] },
  {
    artist: "bala-bombom-e-chocolate",
    songs: ["fissuras-de-um-casal", "caixa-postal"],
  },
  { artist: "kiloucura", songs: ["meu-casamento"] },
  { artist: "karametade", songs: ["se-melhorar-estraga", "decisao"] },
  { artist: "ronaldo-e-os-barcellos", songs: ["feliz-aniversario"] },
  { artist: "waguinho", songs: ["mina-de-fe"] },
  { artist: "sem-compromisso", songs: ["nascente"] },
  { artist: "cor-da-pele", songs: ["desengano"] },
  { artist: "eliana-de-lima", songs: ["desejo-de-amar"] },
  { artist: "malicia", songs: ["primeiro-beijo"] },
  { artist: "sampa-crew", songs: ["eterno-amor"] },
  { artist: "e-demais", songs: ["video-clip"] },
  { artist: "juventude-s", songs: ["historia-de-amor"] },
  {
    artist: "terra-samba",
    songs: [
      "liberar-geral",
      "carrinho-de-mao",
      "ta-tirando-onda",
      "deus-e-brasileiro",
      "na-manteiga",
      "banho-de-chuveiro",
      "carrinho-de-mao",
      "liberar-geral",
      "carrinho-de-mao",
      "banho-de-chuveiro",
      "ta-tirando-onda",
      "liberar-geral",
      "deus-e-brasileiro",
      "ta-tirando-onda",
      "treme-terra",
      "carrinho-de-mao",
      "banho-de-chuveiro",
      "na-manteiga",
    ],
  },
  {
    artist: "e-o-tchan",
    songs: [
      "danca-da-cordinha",
      "a-danca-do-bumbum",
      "pega-no-bumbum",
      "pau-que-nasce-torto",
      "ralando-o-tchan-danca-do-ventre",
      "paquerei",
      "a-nova-loira-do-tchan",
      "danca-do-poe-poe",
      "e-o-tchan-medley:-pau-que-nasce-torto",
      "danca-da-cordinha",
      "a-danca-do-bumbum",
      "ralando-o-tchan-danca-do-ventre",
      "na-boquinha-da-garrafa",
      "paquerei",
      "e-o-tchan-medley:-pau-que-nasce-torto",
      "a-danca-do-bumbum",
      "danca-da-cordinha",
      "a-lourinha",
      "estatua",
      "melo-do-tchaco-ii-danca-gostosa",
      "ralando-o-tchan-danca-do-ventre",
      "bambole",
      "mao-boba",
      "danca-do-poe-poe",
      "disque-tchan-alo-e-tchan",
      "tchan-na-selva",
      "lamba-tchan",
      "quebradeira-joelhinho-cabeca",
      "tribotchan",
      "a-nova-loira-do-tchan",
      "danca-da-cordinha",
    ],
  },
  {
    artist: "ara-ketu",
    songs: [
      "mal-acostumada",
      "pipoca",
      "pra-levantar-a-poeira",
      "fanfarra",
      "pipoca",
      "ara-ketu-bom-demais",
      "ara-ketu-bom-demais",
      "mal-acostumada",
      "ara-ketu-bom-demais",
      "pipoca",
      "fanfarra",
      "ziriguidum",
      "ara-ketu-bom-demais",
      "mal-acostumada",
      "pipoca",
      "o-ere",
    ],
  },
  {
    artist: "banda-beijo",
    songs: [
      "bate-lata",
      "perae",
      "bate-lata",
      "perae",
      "estrela-primeira-amor-eu-fico",
      "perae",
      "bate-lata",
    ],
  },
  {
    artist: "banda-eva",
    songs: [
      "carro-velho",
      "me-abraca",
      "vem-meu-amor",
      "eva-eva",
      "beleza-rara",
      "arere",
      "alo-paixao",
      "me-abraca",
      "levada-louca",
      "carro-velho",
      "leva-eu",
      "we-are-the-world-of-carnaval",
      "levada-louca",
      "tic-tic-tac",
      "quimica-perfeita-quimica-perfecta",
      "carro-velho",
      "de-ladinho",
      "arere",
      "flores-sonho-epico",
      "leva-eu",
      "me-abraca",
      "alo-paixao",
      "vem-meu-amor",
      "eva-eva",
      "beleza-rara",
    ],
  },
  {
    artist: "chiclete-com-banana",
    songs: [
      "cabelo-raspadinho",
      "voa-voa",
      "100%-voce",
      "diga-que-valeu",
      "amor-perfeito",
      "100%-voce",
      "amor-perfeito",
      "diga-que-valeu",
      "voa-voa",
      "cara-caramba-sou-camaleao",
      "chicleteiro-eu-chicleteira-ela",
      "foi-por-esse-amor",
      "100%-voce",
    ],
  },
  {
    artist: "banda-reflexu's",
    songs: ["madagascar-olodum", "madagascar-olodum"],
  },
  {
    artist: "olodum",
    songs: [
      "nossa-gente-avisa-la",
      "i-miss-her",
      "alegria-geral",
      "requebra",
      "deusa-do-amor",
      "nossa-gente-avisa-la",
      "requebra",
      "nossa-gente-avisa-la",
      "alegria-geral",
      "requebra",
      "reconvexo",
    ],
  },
  {
    artist: "babado-novo",
    songs: [
      "safado-cachorro-sem",
      "safado-cachorro-sem",
      "eu-fico",
      "amor-perfeito",
      "bola-de-sabao",
      "amor-perfeito",
      "safado-cachorro-sem",
      "e-saudade",
    ],
  },
  { artist: "banda-mar-azul", songs: ["xibom-bombon"] },
  {
    artist: "xanddy-harmonia",
    songs: [
      "agachadinho",
      "nossa-paradinha",
      "vem-nenem",
      "desafio",
      "o-rodo",
      "desafio",
      "vem-nenem",
      "nossa-paradinha",
      "agachadinho",
      "vem-nenem",
      "desafio",
      "agachadinho",
      "nossa-paradinha",
      "o-rodo",
    ],
  },
  {
    artist: "daniela-mercury",
    songs: [
      "rapunzel",
      "o-canto-da-cidade",
      "nobre-vagabundo",
      "swing-da-cor",
      "rapunzel",
      "musica-de-rua",
      "baianidade-nago",
      "o-canto-da-cidade",
      "nobre-vagabundo",
      "swing-da-cor",
      "rapunzel",
    ],
  },
  {
    artist: "bamdamel",
    songs: [
      "farao-divindade-do-egito",
      "festa-na-bahia",
      "prefixo-de-verao",
      "baianidade-nago",
      "bateu-saudade",
      "baianidade-nago",
      "prefixo-de-verao",
      "festa-na-bahia",
    ],
  },
  { artist: "raca-pura", songs: ["juliana", "o-pinto", "juliana"] },
  {
    artist: "ivete-sangalo",
    songs: [
      "na-base-do-beijo",
      "farao-divindade-do-egito",
      "canibal",
      "chorando-se-foi",
      "eva",
      "pais-tropical",
      "canibal",
      "flores-sonho-epico",
      "abalou",
      "pais-tropical",
      "nao-me-conte-seus-problemas",
      "canibal",
    ],
  },
  {
    artist: "timbalada",
    songs: [
      "agua-mineral",
      "beija",
      "toque-de-timbaleiro",
      "mimar-voce",
      "margarida-perfumada",
      "medley:-se-voce-se-for",
      "zorra",
      "a-latinha",
      "rale",
      "canto-pro-mar",
      "beija",
      "margarida-perfumada",
      "agua-mineral",
      "a-latinha",
      "beija",
      "agua-mineral",
      "margarida-perfumada",
      "mimar-voce",
    ],
  },
  {
    artist: "netinho",
    songs: [
      "preciso-de-voce",
      "capricho-dos-deuses",
      "milla",
      "beijo-na-boca",
      "estrela-primeira-amor-eu-fico",
      "milla",
      "preciso-de-voce",
      "beijo-na-boca",
      "fim-de-semana",
      "capricho-dos-deuses",
      "milla",
      "preciso-de-voce",
      "beijo-na-boca",
      "menina",
      "fim-de-semana",
      "total-total",
      "pra-te-ter-aqui",
      "beijo-na-boca",
    ],
  },
  {
    artist: "cheiro-de-amor",
    songs: [
      "vai-sacudir-vai-abalar",
      "lero",
      "quixabeira",
      "a-danca-da-sensual",
      "vai-sacudir-vai-abalar",
      "quixabeira",
      "vai-sacudir-vai-abalar",
      "aue",
      "pega-no-balanco",
      "a-danca-da-sensual",
      "quixabeira",
      "aviaozinho",
    ],
  },
  {
    artist: "asa-de-aguia",
    songs: [
      "danca-do-vampiro",
      "nao-tem-lua",
      "nao-tem-lua",
      "danca-do-vampiro",
      "manivela",
      "xo-satanas",
      "xo-satanas",
      "danca-do-vampiro",
      "manivela",
    ],
  },
  {
    artist: "margareth-menezes",
    songs: ["dandalunda", "farao", "farao", "farao", "dandalunda"],
  },
  {
    artist: "tchakabum",
    songs: [
      "onda-onda-olha-a-onda",
      "danca-da-maozinha",
      "danca-da-maozinha",
      "onda-onda-olha-a-onda",
      "explosao",
      "tesouro-do-pirata",
    ],
  },
  { artist: "claudia-leitte", songs: ["largadinho", "beijar-na-boca"] },
  {
    artist: "gilmelandia",
    songs: ["maionese-mayonesa", "bate-lata", "maionese-mayonesa"],
  },
  {
    artist: "bell-marques",
    songs: [
      "vou-te-amar-o-ano-inteiro",
      "cabelo-raspadinho",
      "voa-voa",
      "selva-branca",
      "gritos-de-guerra",
      "amar-voce-nao-doi",
      "100%-voce",
      "vumbora-amar",
      "menina-me-da-seu-amor",
      "durvalino-meu-rei",
      "chamego",
      "meu-cabelo-duro-e-assim",
      "cara-caramba-sou-camaleao",
      "eu-fui-atras-de-um-caminhao",
      "bem",
      "foi-por-esse-amor",
      "mude-esse-mundo",
      "cabelo-raspadinho",
    ],
  },
  { artist: "jammil-e-uma-noites", songs: ["praieiro"] },
  { artist: "braga-boys", songs: ["a-bomba"] },
  { artist: "as-meninas", songs: ["xibom-bombom", "xibom-bom"] },
  { artist: "psirico", songs: ["lepo-lepo", "sabonete"] },
  {
    artist: "ricardo-chaves",
    songs: ["o-bicho", "acabou", "deitar-e-rolar", "o-bicho"],
  },
  { artist: "carrapicho", songs: ["tic-tic-tac"] },
  { artist: "luiz-caldas", songs: ["haja-amor", "tieta", "fricote"] },
  { artist: "beto-barbosa", songs: ["adocica", "preta"] },
  { artist: "axe-90-graus", songs: ["to-fraco"] },
  { artist: "parangole", songs: ["tchubirabirom", "rebolation"] },
  { artist: "pega-no-compasso", songs: ["danca-do-compasso"] },
  {
    artist: "companhia-do-pagode",
    songs: ["na-danca-do-strip", "sanduiche", "na-boquinha-da-garrafa"],
  },
  { artist: "rapazolla", songs: ["coracao"] },
  { artist: "bom-balanco", songs: ["tic-bom"] },
  {
    artist: "patrulha-do-samba",
    songs: ["rodopiou", "rala-no-pezinho", "swing-de-rua"],
  },
  { artist: "ile-aiye", songs: ["o-mais-belo-dos-belos"] },
  {
    artist: "shakira",
    songs: [
      "whenever-wherever",
      "estoy-aqui",
      "hips-don't-lie-feat-wyclef-jean",
      "la-tortura-feat-alejandro-sanz",
    ],
  },
  { artist: "pnk", songs: ["get-the-party-started", "don't-let-me-get-me"] },
  {
    artist: "britney-spears",
    songs: [
      "oopsi-did-it-again",
      "toxic",
      "overprotected",
      "baby-one-more-time",
      "i'm-a-slave-4-u",
      "you-drive-me-crazy",
      "born-to-make-you-happy",
    ],
  },
  { artist: "rouge", songs: ["brilha-la-luna"] },
  { artist: "destiny's-child", songs: ["lose-my-breath", "say-my-name"] },
  {
    artist: "jennifer-lopez",
    songs: ["if-you-had-my-love", "jenny-from-the-block", "get-right"],
  },
  {
    artist: "justin-timberlake",
    songs: ["rock-your-body", "cry-me-a-river", "sexyback"],
  },
  { artist: "mariah-carey", songs: ["we-belong-together"] },
  { artist: "ricky-martin", songs: ["livin'-la-vida-loca"] },
  { artist: "black-eyed-peas", songs: ["shut-up", "pump-it", "my-humps"] },
  {
    artist: "backstreet-boys",
    songs: [
      "as-long-as-you-love-me",
      "i-want-it-that-way",
      "everybody-backstreet's-back",
    ],
  },
  {
    artist: "rihanna",
    songs: [
      "sos",
      "don't-stop-the-music",
      "disturbia",
      "umbrella",
      "pon-de-replay",
    ],
  },
  {
    artist: "beyonce",
    songs: [
      "naughty-girl",
      "baby-boy-feat-sean-paul",
      "crazy-in-love-feat-jay",
    ],
  },
  {
    artist: "*nsync",
    songs: [
      "bye-bye-bye",
      "tearin'-up-my-heart",
      "it's-gonna-be-me",
      "i-want-you-back",
      "pop",
    ],
  },
  {
    artist: "christina-aguilera",
    songs: [
      "lady-marmalade",
      "dirrty-feat-redman",
      "genie-in-a-bottle-album-version",
      "fighter",
      "ain't-no-other-man",
      "candyman",
    ],
  },
  {
    artist: "the-pussycat-dolls",
    songs: ["don't-cha", "buttons", "wait-a-minute", "i-hate-this-part"],
  },
  { artist: "five", songs: ["everybody-get-up"] },
  { artist: "santana", songs: ["the-game-of-love-feat-michelle-branch"] },
  { artist: "outkast", songs: ["hey-ya"] },
  { artist: "vanessa-carlton", songs: ["a-thousand-miles"] },
  { artist: "spice-girls", songs: ["wannabe", "spice-up-your-life"] },
  { artist: "usher", songs: ["yeah-feat-lil-jon-e-ludacris"] },
  {
    artist: "avril-lavigne",
    songs: [
      "complicated",
      "don't-tell-me",
      "my-happy-ending",
      "nobody's-home",
      "sk8er-boi",
      "i'm-with-you",
    ],
  },
  { artist: "ashlee-simpson", songs: ["pieces-of-me"] },
  { artist: "jordin-sparks", songs: ["tattoo", "no-air-feat-chris-brown"] },
  {
    artist: "kylie-minogue",
    songs: ["can't-get-you-out-of-my-head", "in-my-arms", "red-blooded-woman"],
  },
  {
    artist: "michael-jackson",
    songs: ["black-or-white", "bad", "billie-jean", "thriller"],
  },
  {
    artist: "chris-brown",
    songs: ["gimme-that", "kiss-kiss-feat-t", "wall-to-wall"],
  },
  {
    artist: "kelly-clarkson",
    songs: [
      "breakaway",
      "since-u-been-gone",
      "behind-these-hazel-eyes",
      "because-of-you",
      "gone",
    ],
  },
  { artist: "hilary-duff", songs: ["with-love", "come-clean"] },
  {
    artist: "maroon-5",
    songs: ["this-love", "if-i-never-see-your-face-again", "wake-up-call"],
  },
  {
    artist: "sandy-e-junior",
    songs: [
      "nao-da-pra-nao-pensar",
      "quando-voce-passa-turu-turu-turuturu",
      "love-never-fails",
    ],
  },
  { artist: "wanessa-camargo", songs: ["amor-amor"] },
  { artist: "panic-at-the-disco", songs: ["i-write-sins-not-tragedies"] },
  { artist: "kat-deluna", songs: ["whine-up-feat-elephant-man"] },
  { artist: "the-calling", songs: ["wherever-you-will-go"] },
  { artist: "ciara", songs: ["one-two-step-feat-missy-elliott"] },
  { artist: "lindsay-lohan", songs: ["rumors"] },
  { artist: "natasha-bedingfield", songs: ["unwritten"] },
  { artist: "evanescence", songs: ["going-under"] },
];
