export const songList = [
  {
    artist: "os-paralamas-do-sucesso",
    songs: [
      "meu-erro",
      "aonde-quer-que-eu-va",
      "lanterna-dos-afogados",
      "uma-brasileira",
      "oculos",
      "vital-e-sua-moto",
      "ela-disse-adeus",
      "cuide-bem-do-seu-amor",
      "caleidoscopio",
      "voce",
      "lourinha-bombril-parate-y-mira",
      "cuide-bem-do-seu-amor",
      "seguindo-estrelas",
      "aonde-quer-que-eu-va",
      "cuide-bem-do-seu-amor",
      "aonde-quer-que-eu-va",
      "lanterna-dos-afogados",
    ],
  },
  {
    artist: "nenhum-de-nos",
    songs: [
      "o-astronauta-de-marmore-starman",
      "camila-camila",
      "amanha-ou-depois",
      "o-astronauta-de-marmore",
    ],
  },
  {
    artist: "engenheiros-do-hawaii",
    songs: [
      "infinita-highway",
      "era-um-garoto-que-como-eu-amava-os-beatles-e-os-rolling-stones",
      "o-papa-e-pop",
      "pra-ficar-legal",
      "ate-o-fim",
      "nem1-dia",
      "surfando-karmas-e-dna",
      "era-um-garoto-que-como-eu-amava-os-beatles-e-os-rolling-stones",
      "pra-ser-sincero",
    ],
  },
  {
    artist: "barao-vermelho",
    songs: [
      "bete-balanco",
      "por-voce",
      "pro-dia-nascer-feliz",
      "maior-abandonado",
      "puro-extase",
      "amor-meu-grande-amor",
      "vem-quente-que-eu-estou-fervendo",
      "puro-extase",
      "por-voce",
    ],
  },
  {
    artist: "frejat",
    songs: [
      "segredos",
      "amor-pra-recomecar",
      "por-voce",
      "segredos",
      "segredos",
    ],
  },
  { artist: "cazuza", songs: ["exagerado", "ideologia"] },
  {
    artist: "ultraje-a-rigor",
    songs: [
      "ciume",
      "inutil",
      "nos-vamos-invadir-sua-praia",
      "rebelde-sem-causa",
    ],
  },
  { artist: "ira", songs: ["envelheco-na-cidade"] },
  {
    artist: "capital-inicial",
    songs: [
      "veraneio-vascaina",
      "primeiros-erros-chove-feat-kiko-zambianchi",
      "a-sua-maneira-de-musica-ligeira",
      "natasha",
      "nao-olhe-pra-tras",
      "fogo",
      "aqui",
      "musica-urbana",
      "o-passageiro-the-passenger",
      "a-sua-maneira-de-musica-ligeira",
      "a-sua-maneira-de-musica-ligera",
    ],
  },
  {
    artist: "titas",
    songs: [
      "epitafio",
      "os-cegos-do-castelo",
      "enquanto-houver-sol",
      "isso",
      "marvin",
      "e-preciso-saber-viver",
      "homem-primata",
      "epitafio",
      "epitafio",
      "enquanto-houver-sol",
      "enquanto-houver-sol",
    ],
  },
  { artist: "nando-reis-e-os-infernais", songs: ["all-star"] },
  {
    artist: "nando-reis",
    songs: [
      "relicario",
      "luz-dos-olhos",
      "sou-dela",
      "resposta",
      "relicario",
      "pra-voce-guardei-o-amor",
      "onde-voce-mora",
      "pra-voce-guardei-o-amor",
      "por-onde-andei",
      "sei",
    ],
  },
  {
    artist: "cassia-eller",
    songs: [
      "o-segundo-sol",
      "malandragem",
      "malandragem",
      "relicario",
      "o-segundo-sol",
    ],
  },
  { artist: "biquini-cavadao", songs: ["tedio", "dani", "janaina"] },
  {
    artist: "blitz",
    songs: ["voce-nao-soube-me-amar", "a-dois-passos-do-paraiso"],
  },
  {
    artist: "kid-abelha",
    songs: [
      "na-rua-na-chuva-na-fazenda-casinha-de-sape",
      "como-eu-quero",
      "lagrimas-e-chuva",
      "nada-sei-apneia",
      "no-seu-lugar",
      "fixacao",
      "eu-so-penso-em-voce",
      "nao-vou-ficar",
      "como-eu-quero",
      "nada-sei-apneia",
    ],
  },
  { artist: "herva-doce", songs: ["amante-profissional"] },
  { artist: "ritchie", songs: ["menina-veneno"] },
  { artist: "plebe-rude", songs: ["ate-quando-esperar"] },
  {
    artist: "legiao-urbana",
    songs: [
      "tempo-perdido",
      "eduardo-e-monica",
      "sera",
      "indios",
      "que-pais-e-este",
      "ainda-e-cedo",
      "geracao-coca",
      "faroeste-caboclo",
      "vento-no-litoral",
      "pais-e-filhos",
    ],
  },
  {
    artist: "skank",
    songs: [
      "resposta",
      "sutilmente",
      "ainda-gosto-dela",
      "vou-deixar",
      "amores-imperfeitos",
      "balada-do-amor-inabalavel",
      "dois-rios",
      "e-proibido-fumar",
      "e-uma-partida-de-futebol",
      "garota-nacional",
      "jackie-tequila",
      "mil-acasos",
      "pacato-cidadao",
      "saideira",
      "tao-seu",
      "vamos-fugir",
      "te-ver",
      "sutilmente",
      "vou-deixar",
      "mil-acasos",
      "tres-lados",
      "dois-rios",
      "ainda-gosto-dela",
      "jackie-tequila",
      "vamos-fugir",
      "ainda-gosto-dela",
      "sutilmente",
    ],
  },
  {
    artist: "o-rappa",
    songs: [
      "hey-joe-feat-marcelo-d2",
      "ile-aye",
      "vapor-barato",
      "a-feira",
      "pescador-de-ilusoes",
      "pescador-de-ilusoes",
    ],
  },
  {
    artist: "charlie-brown-jr",
    songs: [
      "so-os-loucos-sabem",
      "meu-novo-mundo",
      "dias-de-luta-dias-de-gloria",
      "senhor-do-tempo",
      "lutar-pelo-que-e-meu",
      "ela-vai-voltar-todos-os-defeitos-de-uma-mulher-perfeita",
      "so-por-uma-noite",
      "me-encontra",
      "tudo-mudar",
      "lugar-ao-sol",
      "ela-vai-voltar-todos-os-defeitos-de-uma-mulher-perfeita",
      "zoio-de-lula",
      "dias-de-luta-dias-de-gloria",
    ],
  },
  {
    artist: "detonautas-roque-clube",
    songs: [
      "quando-o-sol-se-for",
      "outro-lugar",
      "olhos-certos",
      "so-por-hoje",
      "to-aprendendo-a-viver-sem-voce",
      "olhos-certos",
      "voce-me-faz-tao-bem",
    ],
  },
  {
    artist: "cpm-22",
    songs: [
      "tarde-de-outubro",
      "um-minuto-para-o-fim-do-mundo",
      "um-minuto-para-o-fim-do-mundo",
    ],
  },
  { artist: "strike", songs: ["paraiso-proibido", "o-jogo-virou"] },
  { artist: "cogumelo-plutao", songs: ["esperando-na-janela"] },
  {
    artist: "marco-prates",
    songs: [
      "lugar-ao-sol",
      "indios",
      "por-enquanto",
      "eu-sei",
      "dia-especial",
      "pra-ser-sincero",
      "segredos",
    ],
  },
  {
    artist: "armandinho",
    songs: [
      "outra-vida",
      "amor-de-primavera",
      "ursinho-de-dormir",
      "desenho-de-deus",
      "desenho-de-deus",
    ],
  },
  {
    artist: "pitty",
    songs: [
      "equalize",
      "me-adora",
      "me-adora",
      "equalize",
      "na-sua-estante",
      "equalize",
      "me-adora",
      "na-sua-estante",
      "equalize",
    ],
  },
  {
    artist: "nx-zero",
    songs: ["cedo-ou-tarde", "so-rezo", "razoes-e-emocoes", "alem-de-mim"],
  },
  {
    artist: "los-hermanos",
    songs: ["ultimo-romance", "o-vencedor", "anna-julia"],
  },
  {
    artist: "quinho",
    songs: [
      "recomecar",
      "outra-vez",
      "acho-melhor-voce-partir",
      "nem-voce-nem-ninguem",
      "sheyla",
    ],
  },
  { artist: "ls-jack", songs: ["carla", "sem-radar", "carla"] },
  {
    artist: "marcozero",
    songs: [
      "nada-mais-faz-sentido-acustico",
      "mil-andares-acustico",
      "eu-acustico",
      "cartas-para-o-oriente-acustico",
      "recomecar-acustico",
      "nao-me-deixe-esperar-acustico",
      "inverno-acustico",
      "da-sua-vida-acustico",
    ],
  },
  {
    artist: "jota-quest",
    songs: [
      "so-hoje",
      "o-sol",
      "o-que-eu-tambem-nao-entendo",
      "facil",
      "so-hoje",
      "alem-do-horizonte",
      "dias-melhores",
      "o-que-eu-tambem-nao-entendo",
    ],
  },
  { artist: "gira", songs: ["quando-o-carnaval-chegar"] },
  {
    artist: "walace-fonseca",
    songs: [
      "so-no-amor",
      "enquanto-houver",
      "desejo",
      "desejo-uma-vida-a-ti",
      "anjo-sol",
      "nem-tao-longe",
      "mais-um-ceu",
      "deixe-o-sol-brilhar",
      "o-dia-sobre-a-noite",
    ],
  },
  {
    artist: "papas-da-lingua",
    songs: [
      "disco-rock",
      "vem-pra-ca",
      "po-de-pimenta",
      "sorte",
      "eu-sei",
      "eu-sei",
    ],
  },
  { artist: "tihuana", songs: ["que-ves"] },
  { artist: "o-surto", songs: ["a-cera", "tudo-e-possivel"] },
  {
    artist: "a-metropole",
    songs: [
      "insatisfacao",
      "nada-e-facil",
      "foi-voce-quem-quis",
      "nem-voce-nem-ninguem",
    ],
  },
  { artist: "reacao-em-cadeia", songs: ["me-odeie"] },
  { artist: "moptop", songs: ["aonde-quer-chegar"] },
  { artist: "gram", songs: ["voce-pode-ir-na-janela"] },
  { artist: "cachorro-grande", songs: ["sinceramente"] },
  {
    artist: "fresno",
    songs: ["desde-quando-voce-se-foi", "quebre-as-correntes"],
  },
  { artist: "henry-freitas", songs: ["tem-cafe"] },
  { artist: "roda-de-pagodao", songs: ["a-nova-geracao-10"] },
  { artist: "toque-dez", songs: ["postura", "daqui-pra-sempre", "meio-termo"] },
  { artist: "nadson-o-ferinha", songs: ["clima-frio"] },
  { artist: "bregao-du-valle", songs: ["sequencia-do-mete"] },
  {
    artist: "rai-saia-rodada",
    songs: ["5-da-manha", "bebe-e-vem-me-procurar", "tapao-na-raba"],
  },
  { artist: "calcinha-preta", songs: ["amor-dividido"] },
  { artist: "kleo-dibah", songs: ["se-eu-me-entregar"] },
  { artist: "oh-major", songs: ["bloco-que-parafernalia"] },
  {
    artist: "vitor-fernandes",
    songs: ["ai-ce-liga", "minha-saudade", "acaso"],
  },
  {
    artist: "gusttavo-lima",
    songs: ["mala-dos-porta", "nao-me-arranha", "carreira-solo"],
  },
  { artist: "raphaela-santos", songs: ["quem-e-o-louco-entre-nos"] },
  {
    artist: "joao-gomes",
    songs: ["virando-tanto-faz", "meu-pedaco-de-pecado"],
  },
  { artist: "tinho-oh-drama", songs: ["fode-sacaninha"] },
  {
    artist: "leo-santana",
    songs: [
      "cama-repetida",
      "golzinho-vermelho",
      "cabare",
      "contatinho",
      "contatinho",
    ],
  },
  { artist: "heitor-costa", songs: ["passaro-noturno", "pior-parte"] },
  { artist: "o-dono-da-loja", songs: ["pula-pula"] },
  { artist: "nattan", songs: ["a-gente-se-entrega", "morena"] },
  { artist: "oh-polemico", songs: ["rufo-rufo"] },
  { artist: "o-kannalha", songs: ["nego-doce"] },
  { artist: "parangole", songs: ["perna-bamba"] },
  { artist: "simone-mendes", songs: ["voce-mereceu"] },
  { artist: "filhos-de-jorge", songs: ["a-cor-do-amor"] },
  {
    artist: "ivete-sangalo",
    songs: [
      "macetando",
      "macetando",
      "cria-da-ivete",
      "nao-precisa-mudar",
      "se-eu-nao-te-amasse-tanto-assim",
      "nao-precisa-mudar",
      "se-eu-nao-te-amasse-tanto-assim",
    ],
  },
  { artist: "dr-jonn", songs: ["bloquinho-do-dr"] },
  { artist: "igor-kannario", songs: ["bota-pra-virar"] },
  { artist: "black-style", songs: ["quem-bota-tudao"] },
  { artist: "o-maestro", songs: ["pot"] },
  { artist: "rachel-reis", songs: ["deusa-do-amor"] },
  { artist: "rei-delas", songs: ["bota-empurra"] },
  { artist: "ze-paredao", songs: ["medley-do-zecas"] },
  { artist: "banda-hit-hal-[oficial]", songs: ["senta-na-peca-do-cac"] },
  {
    artist: "ze-neto-e-cristiano",
    songs: [
      "patio-do-posto",
      "barulho-do-foguete",
      "ferida-curada",
      "alo-ambev-segue-sua-vida",
      "largado-as-tracas",
      "vamo-tomar-uma",
      "bebi-minha-bicicleta-coracao-falido",
    ],
  },
  {
    artist: "banda-bg-da-putaria",
    songs: ["baile-do-bg-20:-toma-ferro-de-novo"],
  },
  { artist: "thiago-aquino", songs: ["barulho-do-foguete"] },
  {
    artist: "matheus-e-kauan",
    songs: [
      "nao-vitalicio-nunca-mais",
      "te-assumi-pro-brasil",
      "quarta-cadeira",
      "litrao",
      "e-problema",
      "vagabundo",
    ],
  },
  { artist: "xanddy-harmonia", songs: ["descontrolada"] },
  {
    artist: "diego-e-victor-hugo",
    songs: [
      "cheiro-e-cabelo",
      "a-culpa-e-do-meu-grau-feat-ze-neto-e-cristiano",
      "pisadinha",
    ],
  },
  { artist: "rd-gosta", songs: ["bloco-putaria-20"] },
  { artist: "pittybull", songs: ["bloco-nova-geracao"] },
  {
    artist: "ludmilla",
    songs: [
      "nao-e-por-maldade",
      "rainha-da-favela",
      "mande-um-sinal",
      "ela-nao",
      "sintoma-de-amor",
      "numanice-lud-session",
      "diz-pra-mim",
      "me-arrepender",
      "medley-lud-session",
      "faz-uma-loucura-por-mim",
      "maldivas",
      "a-boba-fui-eu",
    ],
  },
  { artist: "ah-chapa", songs: ["bloquinho-putete-10"] },
  { artist: "felipe-araujo", songs: ["ultima-noite", "atrasadinha"] },
  { artist: "diogo-nogueira", songs: ["pe-na-areia"] },
  {
    artist: "revelacao",
    songs: [
      "coracao-radiante",
      "deixa-alagar",
      "velocidade-da-luz",
      "grades-do-coracao",
      "deixa-acontecer",
      "o-show-tem-que-continuar",
      "fala-baixinho-shiii",
      "so-depois",
      "deixa-acontecer",
    ],
  },
  { artist: "art-popular", songs: ["temporal"] },
  { artist: "pedro-sampaio", songs: ["vai-menina"] },
  {
    artist: "imaginasamba",
    songs: [
      "me-assume-ou-me-esquece",
      "pega-pega-participacao-especial-de-jojo-maronttinni",
    ],
  },
  {
    artist: "menos-e-mais",
    songs: [
      "lapada-dela",
      "pot",
      "adorei",
      "pot",
      "amor-falsificado",
      "quando-voce-me-beija",
    ],
  },
  { artist: "mc-cabelinho", songs: ["nossa-musica"] },
  {
    artist: "luisa-sonza",
    songs: ["campo-de-morango", "surreal", "principalmente-me-sinto-arrasada"],
  },
  {
    artist: "so-pra-contrariar",
    songs: ["que-se-chama-amor", "que-se-chama-amor"],
  },
  { artist: "sony-no-beat", songs: ["parecia-tempestade"] },
  { artist: "anitta", songs: ["savage-funk", "some-que-ele-vem-atras"] },
  { artist: "kamisa-10", songs: ["nosso-role"] },
  {
    artist: "henrique-e-juliano",
    songs: [
      "vidinha-de-balada",
      "arranhao",
      "ficamento",
      "de-garrafa-a-pior",
      "gaiola",
    ],
  },
  { artist: "iza", songs: ["dona-de-mim", "pesadao"] },
  { artist: "flora-matos", songs: ["piloto"] },
  { artist: "vou-pro-sereno", songs: ["teu-segredo"] },
  { artist: "malibu", songs: ["cigana"] },
  { artist: "davi-kneip", songs: ["sentadona-remix-s2"] },
  {
    artist: "marilia-mendonca",
    songs: [
      "supera",
      "como-faz-com-ela",
      "bem-pior-que-eu",
      "supera",
      "troca-de-calcada",
      "presepada",
      "bebi-liguei",
      "todo-mundo-vai-sofrer",
    ],
  },
  { artist: "mumuzinho", songs: ["curto-circuito", "eu-mereco-ser-feliz"] },
  { artist: "tribo-da-periferia", songs: ["conspiracao"] },
  { artist: "agroplay", songs: ["dia-de-fluxo"] },
  { artist: "dennis", songs: ["sou-teu-fa"] },
  { artist: "jorge-e-mateus", songs: ["logo-eu", "cheirosa", "tijolao"] },
  {
    artist: "zeca-pagodinho",
    songs: [
      "deixa-a-vida-me-levar",
      "alma-carioca-cristo-redentor-feat-padre-omar-moacyr-luz-toni-garrido-bruno-gouveia-maria-rita-mart'nalia-paula-toller-fernanda-abreu-jorge-aragao-sandra-de-sa-e-fagner",
    ],
  },
  { artist: "exaltasamba-musicas", songs: ["me-apaixonei-pela-pessoa-errada"] },
  { artist: "benzadeus", songs: ["tuntuntun"] },
  { artist: "pixote", songs: ["inseguranca", "nem-de-graca"] },
  { artist: "raca-negra", songs: ["cheia-de-manias"] },
  { artist: "di-proposito", songs: ["manda-audio"] },
  { artist: "pericles", songs: ["supera", "graveto", "pupila"] },
  {
    artist: "tarcisio-do-acordeon",
    songs: ["meia-noite-voce-tem-meu-whatsapp", "nega"],
  },
  {
    artist: "os-baroes-da-pisadinha",
    songs: ["ta-rocheda", "recairei", "amor-da-despedida"],
  },
  { artist: "matheus-fernandes", songs: ["baby-me-atende", "nem-va"] },
  {
    artist: "turma-do-pagode",
    songs: [
      "bebe-e-vem-me-procurar",
      "sua-mae-vai-me-amar",
      "aonde-quer-chegar",
    ],
  },
  {
    artist: "dilsinho",
    songs: ["pessimo-negocio", "sogra", "pouco-a-poucofeat-sorriso-maroto"],
  },
  {
    artist: "atitude-67",
    songs: ["cerveja-de-garrafa-fumaca-que-eu-faco", "saideira"],
  },
  {
    artist: "israel-e-rodolffo",
    songs: ["batom-de-cereja", "so-de-sacanagem"],
  },
  { artist: "joao-gustavo-e-murilo", songs: ["lencol-dobrado"] },
  { artist: "lauana-prado", songs: ["cobaia"] },
  { artist: "molejo", songs: ["cilada"] },
  {
    artist: "wesley-safadao",
    songs: [
      "aquele-1%",
      "ele-e-ele-eu-sou-eu",
      "eu-ja-tava-bem",
      "passatempo",
      "dois-lados",
    ],
  },
  { artist: "mari-fernandez", songs: ["parada-louca", "nao-nao-vou"] },
  { artist: "paulo-e-nathan", songs: ["acabei-de-terminar"] },
  { artist: "mc-kevin-o-chris", songs: ["evoluiu"] },
  { artist: "mc-jacaré", songs: ["vento-forte"] },
  { artist: "joao-bosco-e-gabriel", songs: ["alo-ex"] },
  { artist: "gustavo-mioto", songs: ["solteiro-nao-trai"] },
  { artist: "guilherme-e-benuto", songs: ["sigilo"] },
  { artist: "alok", songs: ["liberdade-quando-o-grave-bate-forte"] },
  { artist: "avine-vinny", songs: ["coracao-cachorro"] },
  { artist: "simone-e-simaria", songs: ["foi-pa-pum"] },
  { artist: "marcia-fellipe", songs: ["quem-me-dera"] },
  { artist: "mc-rogerinho", songs: ["so-voce"] },
  { artist: "felipe-original", songs: ["hit-contagiante"] },
  { artist: "bruno-e-marrone", songs: ["ultimo-beijo"] },
  { artist: "petter-ferraz", songs: ["amor-ou-o-litrao"] },
  {
    artist: "lucas-lucco",
    songs: ["posto-24h-feat-wesley-safadao", "amava-nada"],
  },
  { artist: "ze-felipe", songs: ["so-tem-eu"] },
  { artist: "thiaguinho", songs: ["a-fila-anda"] },
  { artist: "luan-santana", songs: ["sorria"] },
  { artist: "alexandre-pires", songs: ["domingo"] },
  { artist: "murilo-huff", songs: ["esse-barulho"] },
  { artist: "thiago-brava", songs: ["dona-maria"] },
  {
    artist: "mart'nalia",
    songs: [
      "cabide",
      "benditas",
      "don't-worry-be-happy",
      "pra-que-chorar",
      "namora-comigo",
      "insensatez-quelle-grande-sottise",
      "sei-la-a-vida-tem-sempre-razao",
      "boto-meu-povo-na-rua",
      "pe-do-meu-samba",
      "onde-anda-voce",
      "feitico-da-vila",
      "entretanto",
      "alguem-me-avisou",
      "samba-da-bencao",
      "chega",
      "agua-de-chuva-no-mar",
      "aeiou",
      "quem-te-viu-quem-te-ve",
      "o-morro-nao-tem-vez",
      "alegre-menina",
      "volta-por-cima",
      "todo-menino-e-um-rei",
      "linha-do-equador",
      "maracangalha",
      "sem-compromisso",
      "tava-por-ai",
      "tarde-em-itapoa",
      "preciso-dizer-que-te-amo",
      "veneno-veleno",
      "segure-tudo",
      "deixa",
      "tocando-a-vida-rock-bottom",
      "nas-aguas-de-amaralina",
      "ninguem-conhece-ninguem",
      "sem-compromisso",
      "menino-do-rio",
      "o-gato",
      "maria-vai-com-as-outras",
      "ela-e-a-minha-cara",
      "renascer-das-cinzas",
      "cabide",
    ],
  },
  { artist: "sambabook", songs: ["clube-do-samba", "sonho-meu"] },
  { artist: "martinho-da-vila", songs: ["canta-canta-minha-gente"] },
  { artist: "lagum", songs: ["eita-menina"] },
  { artist: "toquinho", songs: ["regra-tres", "aquarela"] },
  { artist: "benditos", songs: ["carol-ou-clarisse"] },
  { artist: "ze-renato", songs: ["batuque-na-cozinha"] },
  {
    artist: "francisco-el-hombre",
    songs: ["o-ensimesmado", "triste-louca-ou-ma"],
  },
  { artist: "junior-almeida", songs: ["uma-chance"] },
  {
    artist: "adriana-calcanhotto",
    songs: [
      "biscate",
      "devolva",
      "vumbora-amar",
      "esquadros",
      "vambora",
      "mentiras",
      "maresia",
      "metade",
      "por-isso-corro-demais",
      "mulher-sem-razao",
      "inverno",
      "mais-feliz",
      "clandestino",
      "cariocas",
      "seu-pensamento",
      "nervos-de-aco",
      "justo-agora",
      "pra-lhe-dizer",
      "naquela-estacao",
      "senhas",
      "cantada-depois-de-ter-voce",
      "eu-sei-que-vou-te-amar",
      "biscate",
      "era-pra-ser",
      "pelos-ares",
      "um-dia-desses",
      "horario-de-verao",
      "medo-de-amar-nº-3",
      "marina",
      "levou-para-o-samba-a-minha-fantasia",
      "me-de-motivo",
      "quem-vem-pra-beira-do-mar",
      "segundos",
      "era-isso-o-amor",
      "e-o-mundo-nao-se-acabou",
      "agua-perrier",
      "back-to-black",
      "metade",
      "devolva",
      "mentiras",
      "maresia",
      "inverno",
      "devolva",
      "esquadros",
    ],
  },
  {
    artist: "maria-bethania",
    songs: ["depois-de-ter-voce", "fera-ferida", "cheiro-de-amor"],
  },
  { artist: "bossacucanova", songs: ["previsao"] },
  { artist: "erasmo-carlos", songs: ["do-fundo-do-meu-coracao"] },
  { artist: "maeana", songs: ["o-amor-me-escolheu"] },
  { artist: "renato-russo", songs: ["esquadros", "mais-uma-vez"] },
  { artist: "fabio-jr", songs: ["mentiras"] },
  { artist: "rubel", songs: ["voce-me-pergunta"] },
  { artist: "johnny-hooker", songs: ["mentiras"] },
  { artist: "mahmundi", songs: ["cariocas"] },
  { artist: "illy", songs: ["o-que-me-cabe"] },
  { artist: "priscila-tossan", songs: ["vambora"] },
  {
    artist: "gabriel-o-pensador",
    songs: [
      "tas-a-ver-feat-adriana-calcanhotto",
      "cachimbo-da-paz-feat-lulu-santos",
    ],
  },
  { artist: "jaloo", songs: ["esquadros"] },
  { artist: "djavan", songs: ["se", "se"] },
  { artist: "leoni", songs: ["garotos-ii"] },
  { artist: "zelia-duncan", songs: ["catedral", "me-revelar"] },
  {
    artist: "cidade-negra",
    songs: [
      "pensamento-acustico",
      "girassol-acustico",
      "a-estrada",
      "a-estrada",
    ],
  },
  {
    artist: "zeca-baleiro",
    songs: ["lenha", "telegrama", "lenha", "telegrama"],
  },
  { artist: "netinho", songs: ["menina", "milla"] },
  {
    artist: "lulu-santos",
    songs: [
      "o-descobridor-dos-sete-mares",
      "apenas-mais-uma-de-amor",
      "apenas-mais-uma-de-amor",
      "toda-forma-de-amor",
      "um-certo-alguem",
      "um-certo-alguem",
    ],
  },
  { artist: "timbalada", songs: ["beija"] },
  {
    artist: "chiclete-com-banana",
    songs: ["cara-caramba-sou-camaleao", "100%-voce"],
  },
  { artist: "raimundos", songs: ["mulher-de-fases"] },
  { artist: "daniela-mercury", songs: ["nobre-vagabundo", "como-vai-voce"] },
  { artist: "mamonas-assassinas", songs: ["robocop-gay"] },
  { artist: "falamansa", songs: ["xote-dos-milagres", "rindo-a-toa"] },
  {
    artist: "tribalistas",
    songs: [
      "velha-infancia",
      "velha-infancia",
      "e-voce",
      "velha-infancia",
      "ja-sei-namorar",
    ],
  },
  { artist: "luciana-mello", songs: ["simples-desejo", "assim-que-se-faz"] },
  {
    artist: "natiruts",
    songs: ["natiruts-reggae-power", "quero-ser-feliz-tambem"],
  },
  {
    artist: "danni-carlos",
    songs: ["coisas-que-eu-sei", "coisas-que-eu-sei", "coisas-que-eu-sei"],
  },
  {
    artist: "jorge-vercillo",
    songs: [
      "final-feliz",
      "monalisa",
      "que-nem-mare",
      "ela-une-todas-as-coisas",
      "final-feliz",
    ],
  },
  {
    artist: "rita-lee",
    songs: [
      "amor-e-sexo",
      "mania-de-voce",
      "amor-e-sexo",
      "ovelha-negra",
      "lanca-perfume",
      "erva-venenosa",
      "caso-serio",
      "minha-vida",
    ],
  },
  { artist: "marjorie-estiano", songs: ["voce-sempre-sera"] },
  { artist: "adriana-partimpim", songs: ["fico-assim-sem-voce"] },
  {
    artist: "marisa-monte",
    songs: [
      "amor-i-love-you",
      "depois",
      "ainda-bem",
      "beija-eu",
      "nao-va-embora",
      "ainda-lembro",
      "o-que-me-importa",
      "a-sua",
      "amor-i-love-you",
      "danca-da-solidao",
      "beija-eu",
    ],
  },
  { artist: "sandy-e-junior", songs: ["a-lenda"] },
  {
    artist: "ana-carolina",
    songs: [
      "encostar-na-tua",
      "pra-rua-me-levar",
      "encostar-na-tua",
      "quem-de-nos-dois-la-mia-storia-tra-le-dita",
      "confesso",
      "garganta",
    ],
  },
  { artist: "pobox", songs: ["papo-de-jacare"] },
  { artist: "melim", songs: ["meu-abrigo"] },
  { artist: "claudinho-e-buchecha", songs: ["quero-te-encontrar"] },
  {
    artist: "tiago-iorc",
    songs: ["amei-te-ver", "coisa-linda", "amei-te-ver"],
  },
  { artist: "gilberto-gil", songs: ["esperando-na-janela"] },
  { artist: "banda-eva", songs: ["vem-meu-amor"] },
  {
    artist: "seu-jorge",
    songs: [
      "burguesinha",
      "quem-nao-quer-sou-eu",
      "amiga-da-minha-mulher",
      "mina-do-condominio",
    ],
  },
  { artist: "vanessa-da-mata", songs: ["ai-ai-ai", "amado", "ainda-bem"] },
  { artist: "paulo-ricardo", songs: ["a-cruz-e-a-espada"] },
  {
    artist: "yuri-corbal",
    songs: ["so-mesmo-o-amor", "cada-um-de-nos-ama-de-um-jeito"],
  },
  { artist: "elis-regina", songs: ["como-nossos-pais", "como-nossos-pais"] },
  { artist: "raul-seixas", songs: ["tente-outra-vez"] },
  { artist: "herois-da-resistencia", songs: ["so-pro-meu-prazer"] },
  { artist: "ze-ramalho", songs: ["chao-de-giz"] },
  { artist: "lenine", songs: ["hoje-eu-quero-sair-so"] },
  { artist: "chimarruts", songs: ["versos-simples"] },
  { artist: "roupa-nova", songs: ["dona"] },
  { artist: "sandy", songs: ["me-espera"] },
  {
    artist: "vander-lee",
    songs: [
      "esperando-avioes",
      "seu-rei",
      "nada-por-nada",
      "onde-deus-possa-me-ouvir",
      "esperando-avioes",
      "tu",
    ],
  },
  { artist: "14-bis", songs: ["planeta-sonho"] },
  { artist: "joao-bosco", songs: ["papel-mache"] },
  { artist: "vinicius", songs: ["eu-sei-que-vou-te-amar"] },
  { artist: "5-a-seco", songs: ["pra-voce-dar-o-nome"] },
  { artist: "banda-go-home", songs: ["a-luz-do-sol"] },
  { artist: "romero-ferro", songs: ["verdadeiro-amor"] },
  { artist: "zizi-possi", songs: ["a-paz-leila-iv", "perigo"] },
  { artist: "marina-lima", songs: ["veneno", "fullgas", "acontecimentos"] },
  { artist: "vanessa-rangel", songs: ["palpite"] },
  { artist: "angela-ro-ro", songs: ["amor-meu-grande-amor"] },
  { artist: "maria-gadu", songs: ["oracao-ao-tempo"] },
  { artist: "duda-beat", songs: ["bixinho"] },
  { artist: "anavitoria", songs: ["ai-amor", "agora-eu-quero-ir", "dengo"] },
  { artist: "banda-do-mar", songs: ["mais-ninguem"] },
  {
    artist: "patricia-marx",
    songs: ["quando-chove", "espelhos-d'agua", "destino"],
  },
  { artist: "roberta-campos", songs: ["minha-felicidade"] },
  { artist: "gal-costa", songs: ["palavras-no-corpo", "azul"] },
];
